services:

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "6379:6379"
    # Set credentials & logging
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on >$REDIS_PASSWORD ~* +@all" > /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redis_data:/var/lib/redis/data

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
      target: dev
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - "./app:/opt/app/app"

volumes:
  pg_data:
  redis_data:
