version: 1
disable_existing_loggers: false

formatters:
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: "%(asctime)s %(levelprefix)s [%(name)s] [%(filename)s:%(lineno)d] - %(client_addr)s - \"%(request_line)s\" %(status_code)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: True
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s %(levelprefix)s [%(name)s] [%(filename)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: True

handlers:
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stderr
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn: # uvicorn debug
    level: DEBUG
    handlers:
      - default
    propagate: yes
  uvicorn.error: # Lifespan
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
  sqlalchemy.engine:
    level: INFO
    handlers:
      - default
    propagate: no

root:
  level: INFO
  handlers:
    - default
  propagate: no
